"""
convert_to_gguf.py
------------------
Step 2 of the CPU deployment pipeline.

Converts the merged FP16 HuggingFace model (./merged_model/) to GGUF
format using the llama.cpp Python library, then quantises it to Q4_K_M
— the sweet spot between quality and CPU speed for a 3B model.

Quantisation guide for Qwen2.5-3B:
  Q8_0    ~3.1 GB  — near-lossless,  slowest  on CPU
  Q4_K_M  ~1.9 GB  — excellent quality/speed balance  ← default
  Q3_K_M  ~1.5 GB  — acceptable quality, fastest
  Q2_K    ~1.1 GB  — noticeable quality loss, use only on very low RAM

Usage:
    .\\venv\\Scripts\\python.exe scripts\\convert_to_gguf.py

Output:
    ./gguf/qwen-ds-finetuned-Q4_K_M.gguf
    ./Modelfile                           (ready for `ollama create`)
"""

import subprocess, sys, struct, os, shutil
from pathlib import Path

MERGED_DIR   = Path("merged_model")
GGUF_DIR     = Path("gguf")
MODEL_NAME   = "qwen-ds-finetuned"
QUANT_TYPE   = "Q4_K_M"
GGUF_OUT     = GGUF_DIR / f"{MODEL_NAME}-{QUANT_TYPE}.gguf"
GGUF_F16     = GGUF_DIR / f"{MODEL_NAME}-f16.gguf"


def check_merged_model():
    if not MERGED_DIR.exists() or not (MERGED_DIR / "config.json").exists():
        print("ERROR: merged_model/ not found.")
        print("Run merge_adapter.py first:")
        print("  .\\venv\\Scripts\\python.exe scripts\\merge_adapter.py")
        sys.exit(1)


def run(cmd, **kwargs):
    """Run a subprocess command, streaming output live."""
    print(f"\n$ {' '.join(str(c) for c in cmd)}\n")
    result = subprocess.run(cmd, **kwargs)
    if result.returncode != 0:
        print(f"\nERROR: command failed with code {result.returncode}")
        sys.exit(result.returncode)
    return result


def find_llama_cpp_convert():
    """
    Locate llama.cpp's convert_hf_to_gguf.py.
    We clone llama.cpp into ./llama.cpp/ if not present.
    """
    script = Path("llama.cpp") / "convert_hf_to_gguf.py"
    if script.exists():
        return script

    print("[*] llama.cpp not found locally — cloning (shallow)...")
    run([
        "git", "clone", "--depth=1",
        "https://github.com/ggml-org/llama.cpp.git",
        "llama.cpp"
    ])
    # Install llama.cpp Python requirements (only gguf-related ones)
    run([
        sys.executable, "-m", "pip", "install",
        "-r", "llama.cpp/requirements/requirements-convert_hf_to_gguf.txt",
        "--quiet"
    ])
    return script


def convert_to_f16_gguf(convert_script: Path):
    """Convert the merged HF model to a float16 GGUF intermediate."""
    GGUF_DIR.mkdir(parents=True, exist_ok=True)
    run([
        sys.executable, str(convert_script),
        str(MERGED_DIR),
        "--outfile", str(GGUF_F16),
        "--outtype", "f16",
    ])


def quantise_gguf():
    """
    Quantise the f16 GGUF to Q4_K_M using llama-quantize.
    Tries the pre-built Windows binary first, then falls back to cmake build.
    """
    quantize_bin = Path("llama.cpp") / "build" / "bin" / "Release" / "llama-quantize.exe"

    if not quantize_bin.exists():
        # Try PATH (if llama.cpp was installed system-wide)
        import shutil as sh
        system_bin = sh.which("llama-quantize") or sh.which("quantize")
        if system_bin:
            quantize_bin = Path(system_bin)
        else:
            print("\n[!] llama-quantize binary not found.")
            print("    Building llama.cpp from source (requires CMake + MSVC/MinGW)...")
            run(["cmake", "-B", "llama.cpp/build", "-S", "llama.cpp", "-DCMAKE_BUILD_TYPE=Release"])
            run(["cmake", "--build", "llama.cpp/build", "--config", "Release", "--target", "llama-quantize"])

    run([str(quantize_bin), str(GGUF_F16), str(GGUF_OUT), QUANT_TYPE])

    # Remove f16 intermediate to save disk space
    GGUF_F16.unlink(missing_ok=True)
    print(f"\n   Removed intermediate f16 file.")


def write_modelfile():
    """
    Write an Ollama Modelfile so the model can be imported with one command.
    """
    modelfile_content = f"""# Ollama Modelfile — Vegapunk DS (Qwen2.5-3B fine-tuned)
# Generated by convert_to_gguf.py

FROM ./{GGUF_OUT}

PARAMETER temperature 0.6
PARAMETER top_p 0.9
PARAMETER repeat_penalty 1.05
PARAMETER num_ctx 4096

SYSTEM \"\"\"You are Vegapunk DS, a world-class AI fine-tuned on data science, machine learning, deep learning, statistical modeling, and data engineering.
Provide mathematically rigorous responses with LaTeX formulas and clean, vectorized code. Always explain your reasoning step-by-step.\"\"\"
"""
    Path("Modelfile").write_text(modelfile_content, encoding="utf-8")
    print(f"   Written: Modelfile")


def print_next_steps():
    print("\n" + "=" * 70)
    print("✅  GGUF CONVERSION COMPLETE")
    print(f"   Model : {GGUF_OUT.resolve()}")
    print(f"   Size  : {GGUF_OUT.stat().st_size / 1e9:.2f} GB")
    print()
    print("── OPTION A: Run with Ollama (easiest) ──────────────────────────────")
    print("   ollama create vegapunk-ds -f Modelfile")
    print("   ollama run vegapunk-ds")
    print()
    print("── OPTION B: Serve via llama.cpp HTTP server ────────────────────────")
    print(f"   llama-server -m {GGUF_OUT} --port 8080 -ngl 0 -c 4096")
    print("   # Then point server.ts HF_REPO_NAME to http://localhost:8080")
    print()
    print("── OPTION C: Upload to Hugging Face as GGUF ─────────────────────────")
    print("   huggingface-cli upload yashvasudeva/qwen-ds-gguf ./gguf/")
    print("=" * 70)


def main():
    print("=" * 70)
    print(f"CONVERT TO GGUF  [{QUANT_TYPE}]")
    print("=" * 70)

    check_merged_model()

    convert_script = find_llama_cpp_convert()
    print(f"\n[1/3] Converting merged model → f16 GGUF ...")
    convert_to_f16_gguf(convert_script)

    print(f"\n[2/3] Quantising f16 → {QUANT_TYPE} ...")
    quantise_gguf()

    print(f"\n[3/3] Writing Modelfile for Ollama ...")
    write_modelfile()

    print_next_steps()


if __name__ == "__main__":
    main()
